// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

export interface Insertpurchase {
  timeAtWork?: unknown;
  userId: string;
  createdAt: Date;
  updatedAt: Date;
}
export interface Updatepurchase {
  timeAtWork?: unknown;
  userId?: string;
  createdAt?: Date;
  updatedAt?: Date;
}
export interface Selectpurchase {
  id: string;
  timeAtWork: unknown;
  userId: string;
  createdAt: Date;
  updatedAt: Date;
}
