// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

export interface Insertsession {
  expiresAt: Date
  token: string
  createdAt: Date
  updatedAt: Date
  ipAddress?: string
  userAgent?: string
  userId: string
}
export interface Updatesession {
  expiresAt?: Date
  token?: string
  createdAt?: Date
  updatedAt?: Date
  ipAddress?: string
  userAgent?: string
  userId?: string
}
export interface Selectsession {
  id: string
  expiresAt: Date
  token: string
  createdAt: Date
  updatedAt: Date
  ipAddress?: string
  userAgent?: string
  userId: string
}
