// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

export interface Insertsetting {
  salary?: unknown
  workingTime?: unknown
  userId: string
  updatedAt: Date
}
export interface Updatesetting {
  salary?: unknown
  workingTime?: unknown
  userId?: string
  updatedAt?: Date
}
export interface Selectsetting {
  id: string
  salary: unknown
  workingTime: unknown
  userId: string
  updatedAt: Date
}
