// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

export interface Insertverification {
  identifier: string
  value: string
  expiresAt: Date
  createdAt: Date
  updatedAt: Date
}
export interface Updateverification {
  identifier?: string
  value?: string
  expiresAt?: Date
  createdAt?: Date
  updatedAt?: Date
}
export interface Selectverification {
  id: string
  identifier: string
  value: string
  expiresAt: Date
  createdAt: Date
  updatedAt: Date
}
