// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

import { z } from "zod";

export const InsertsessionSchema = z.object({
  expiresAt: z.coerce.date(),
  token: z.string(),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
  ipAddress: z.string().nullable().optional(),
  userAgent: z.string().nullable().optional(),
  userId: z.string(),
});

export const UpdatesessionSchema = z.object({
  expiresAt: z.coerce.date().optional(),
  token: z.string().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
  ipAddress: z.string().nullable().optional(),
  userAgent: z.string().nullable().optional(),
  userId: z.string().optional(),
});

export const SelectsessionSchema = z.object({
  id: z.string(),
  expiresAt: z.date(),
  token: z.string(),
  createdAt: z.date(),
  updatedAt: z.date(),
  ipAddress: z.string().nullable(),
  userAgent: z.string().nullable(),
  userId: z.string(),
});

export type InsertsessionInput = z.input<typeof InsertsessionSchema>;
export type UpdatesessionInput = z.input<typeof UpdatesessionSchema>;
export type SelectsessionOutput = z.output<typeof SelectsessionSchema>;
