// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

import { z } from "zod";

export const InsertsettingSchema = z.object({
  salary: z.unknown().optional(),
  workingTime: z.unknown().optional(),
  userId: z.string(),
  updatedAt: z.coerce.date(),
});

export const UpdatesettingSchema = z.object({
  salary: z.unknown().optional(),
  workingTime: z.unknown().optional(),
  userId: z.string().optional(),
  updatedAt: z.coerce.date().optional(),
});

export const SelectsettingSchema = z.object({
  id: z.string(),
  salary: z.unknown(),
  workingTime: z.unknown(),
  userId: z.string(),
  updatedAt: z.date(),
});

export type InsertsettingInput = z.input<typeof InsertsettingSchema>;
export type UpdatesettingInput = z.input<typeof UpdatesettingSchema>;
export type SelectsettingOutput = z.output<typeof SelectsettingSchema>;
