// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

import { z } from 'zod'

export const InsertsettingSchema = z.object({
  salary: z.number().optional(),
  workingTime: z.number().optional(),
  dailyHours: z.number().optional(),
  userId: z.string(),
  updatedAt: z.coerce.date().optional(),
})

export const UpdatesettingSchema = z.object({
  salary: z.number().optional(),
  workingTime: z.number().optional(),
  dailyHours: z.number().optional(),
  userId: z.string().optional(),
  updatedAt: z.coerce.date().optional(),
})

export const SelectsettingSchema = z.object({
  id: z.string(),
  salary: z.number(),
  workingTime: z.number(),
  dailyHours: z.number().optional(),
  userId: z.string(),
  updatedAt: z.date(),
})

export type InsertsettingInput = z.input<typeof InsertsettingSchema>
export type UpdatesettingInput = z.input<typeof UpdatesettingSchema>
export type SelectsettingOutput = z.output<typeof SelectsettingSchema>
