// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

import { z } from "zod";

export const InsertuserSchema = z.object({
  name: z.string(),
  email: z.string(),
  emailVerified: z.boolean().optional(),
  image: z.string().nullable().optional(),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
});

export const UpdateuserSchema = z.object({
  name: z.string().optional(),
  email: z.string().optional(),
  emailVerified: z.boolean().optional(),
  image: z.string().nullable().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
});

export const SelectuserSchema = z.object({
  id: z.string(),
  name: z.string(),
  email: z.string(),
  emailVerified: z.boolean(),
  image: z.string().nullable(),
  createdAt: z.date(),
  updatedAt: z.date(),
});

export type InsertuserInput = z.input<typeof InsertuserSchema>;
export type UpdateuserInput = z.input<typeof UpdateuserSchema>;
export type SelectuserOutput = z.output<typeof SelectuserSchema>;
