// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

import { z } from 'zod'

export const InsertverificationSchema = z.object({
  identifier: z.string(),
  value: z.string(),
  expiresAt: z.coerce.date(),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
})

export const UpdateverificationSchema = z.object({
  identifier: z.string().optional(),
  value: z.string().optional(),
  expiresAt: z.coerce.date().optional(),
  createdAt: z.coerce.date().optional(),
  updatedAt: z.coerce.date().optional(),
})

export const SelectverificationSchema = z.object({
  id: z.string(),
  identifier: z.string(),
  value: z.string(),
  expiresAt: z.date(),
  createdAt: z.date(),
  updatedAt: z.date(),
})

export type InsertverificationInput = z.input<typeof InsertverificationSchema>
export type UpdateverificationInput = z.input<typeof UpdateverificationSchema>
export type SelectverificationOutput = z.output<
  typeof SelectverificationSchema
>
