// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

import { publicProcedure } from "@/lib/orpc";
import type {
  Insertaccount,
  Updateaccount,
  Selectaccount,
} from "./types/account";

export class AccountService {
  static async getAll(): Promise<Selectaccount[]> {
    
    return []
  }
  static async getById(id: number): Promise<Selectaccount | null> {
    return null;
  }
  static async create(input: Insertaccount): Promise<Selectaccount> {
    return input as any;
  }
  static async update(id: number, data: Updateaccount): Promise<Selectaccount> {
    return data as any;
  }
  static async delete(id: number): Promise<boolean> {
    return true;
  }
}
