// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

import db from "../db";
import type {
  Insertpurchase,
  Updatepurchase,
  Selectpurchase,
} from "./types/purchase";

export class PurchaseService {
  static async getAll(): Promise<Selectpurchase[]> {

    const purchases = await db.query.purchase.findMany();

    return purchases;
  }
  static async getById(id: number): Promise<Selectpurchase | null> {
    return null;
  }
  static async create(input: Insertpurchase): Promise<Selectpurchase> {
    return input as any;
  }
  static async update(
    id: number,
    data: Updatepurchase,
  ): Promise<Selectpurchase> {
    return data as any;
  }
  static async delete(id: number): Promise<boolean> {
    return true;
  }
}
