// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

import type {
  Insertsession,
  Updatesession,
  Selectsession,
} from "./types/session";

export class SessionService {
  static async getAll(): Promise<Selectsession[]> {
    return [] as any;
  }
  static async getById(id: number): Promise<Selectsession | null> {
    return null;
  }
  static async create(input: Insertsession): Promise<Selectsession> {
    return input as any;
  }
  static async update(id: number, data: Updatesession): Promise<Selectsession> {
    return data as any;
  }
  static async delete(id: number): Promise<boolean> {
    return true;
  }
}
