// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

import type {
  Insertsetting,
  Updatesetting,
  Selectsetting,
} from "./types/setting";

export class SettingService {
  static async getAll(): Promise<Selectsetting[]> {
    return [] as any;
  }
  static async getById(id: number): Promise<Selectsetting | null> {
    return null;
  }
  static async create(input: Insertsetting): Promise<Selectsetting> {
    return input as any;
  }
  static async update(id: number, data: Updatesetting): Promise<Selectsetting> {
    return data as any;
  }
  static async delete(id: number): Promise<boolean> {
    return true;
  }
}
