// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

import type { Insertstat, Updatestat, Selectstat } from "./types/stat";

export class StatService {
  static async getAll(): Promise<Selectstat[]> {
    return [] as any;
  }
  static async getById(id: number): Promise<Selectstat | null> {
    return null;
  }
  static async create(input: Insertstat): Promise<Selectstat> {
    return input as any;
  }
  static async update(id: number, data: Updatestat): Promise<Selectstat> {
    return data as any;
  }
  static async delete(id: number): Promise<boolean> {
    return true;
  }
}
