// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

import type { Insertuser, Updateuser, Selectuser } from "./types/user";

export class UserService {
  static async getAll(): Promise<Selectuser[]> {
    return [] as any;
  }
  static async getById(id: number): Promise<Selectuser | null> {
    return null;
  }
  static async create(input: Insertuser): Promise<Selectuser> {
    return input as any;
  }
  static async update(id: number, data: Updateuser): Promise<Selectuser> {
    return data as any;
  }
  static async delete(id: number): Promise<boolean> {
    return true;
  }
}
