// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

import type {
  Insertverification,
  Updateverification,
  Selectverification,
} from "./types/verification";

export class VerificationService {
  static async getAll(): Promise<Selectverification[]> {
    return [] as any;
  }
  static async getById(id: number): Promise<Selectverification | null> {
    return null;
  }
  static async create(input: Insertverification): Promise<Selectverification> {
    return input as any;
  }
  static async update(
    id: number,
    data: Updateverification,
  ): Promise<Selectverification> {
    return data as any;
  }
  static async delete(id: number): Promise<boolean> {
    return true;
  }
}
