// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

// Generated by @drzl/generator-orpc
// Router for table: account
import { os } from "@orpc/server";
import { z } from "zod";
import { AccountService } from "../services/accountService";
import {
  InsertaccountSchema as InsertaccountSchema,
  UpdateaccountSchema as UpdateaccountSchema,
  SelectaccountSchema as SelectaccountSchema,
} from "@/validators/zod";

const listAccount = os
  .output(z.array(SelectaccountSchema))
  .handler(async () => {
    return await AccountService.getAll();
  });

const getAccount = os
  .input(z.object({ id: z.number() }))
  .output(SelectaccountSchema.nullable())
  .handler(async ({ input }) => {
    return await AccountService.getById(input.id);
  });

const createAccount = os
  .input(InsertaccountSchema)
  .output(SelectaccountSchema)
  .handler(async ({ input }) => {
    return await AccountService.create(input);
  });

const updateAccount = os
  .input(z.object({ id: z.number(), data: UpdateaccountSchema }))
  .output(SelectaccountSchema)
  .handler(async ({ input }) => {
    return await AccountService.update(input.id, input.data);
  });

const deleteAccount = os
  .input(z.object({ id: z.number() }))
  .output(z.boolean())
  .handler(async ({ input }) => {
    return await AccountService.delete(input.id);
  });

export const accountRouter = {
  list: listAccount,
  get: getAccount,
  create: createAccount,
  update: updateAccount,
  delete: deleteAccount,
};
