// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

import type { RouterClient } from "@orpc/server";
import { accountRouter } from "./accountRouter";
import { purchaseRouter } from "./purchaseRouter";
import { sessionRouter } from "./sessionRouter";
import { settingRouter } from "./settingRouter";
import { statRouter } from "./statRouter";
import { userRouter } from "./userRouter";
import { verificationRouter } from "./verificationRouter";

export const appRouter = {
  account: accountRouter,
  purchase: purchaseRouter,
  session: sessionRouter,
  setting: settingRouter,
  stat: statRouter,
  user: userRouter,
  verification: verificationRouter,
};

// import { protectedProcedure, publicProcedure } from "../lib/orpc";
// import type { RouterClient } from "@orpc/server";

// export const appRouter = {
//   healthCheck: publicProcedure.handler(() => {
//     return "OK";
//   }),
//   privateData: protectedProcedure.handler(({ context }) => {
//     return {
//       message: "This is private",
//       user: context.session?.user,
//     };
//   }),
// };
export type AppRouter = typeof appRouter;
export type AppRouterClient = RouterClient<typeof appRouter>;

