// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

// Generated by @drzl/generator-orpc
// Router for table: purchase
import { os } from "@orpc/server";
import { z } from "zod";
import { PurchaseService } from "../services/purchaseService";
import {
  InsertpurchaseSchema as InsertpurchaseSchema,
  UpdatepurchaseSchema as UpdatepurchaseSchema,
  SelectpurchaseSchema as SelectpurchaseSchema,
} from "@/validators/zod";
import { publicProcedure } from "@/lib/orpc";

const listPurchase = publicProcedure
  .output(z.array(SelectpurchaseSchema))
  .handler(async () => {
    return await PurchaseService.getAll();
  });

const getPurchase = os
  .input(z.object({ id: z.number() }))
  .output(SelectpurchaseSchema.nullable())
  .handler(async ({ input }) => {
    return await PurchaseService.getById(input.id);
  });

const createPurchase = os
  .input(InsertpurchaseSchema)
  .output(SelectpurchaseSchema)
  .handler(async ({ input }) => {
    return await PurchaseService.create(input);
  });

const updatePurchase = os
  .input(z.object({ id: z.number(), data: UpdatepurchaseSchema }))
  .output(SelectpurchaseSchema)
  .handler(async ({ input }) => {
    return await PurchaseService.update(input.id, input.data);
  });

const deletePurchase = os
  .input(z.object({ id: z.number() }))
  .output(z.boolean())
  .handler(async ({ input }) => {
    return await PurchaseService.delete(input.id);
  });

export const purchaseRouter = {
  list: listPurchase,
  get: getPurchase,
  create: createPurchase,
  update: updatePurchase,
  delete: deletePurchase,
};
