// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

// Generated by @drzl/generator-orpc
// Router for table: session
import { os } from "@orpc/server";
import { z } from "zod";
import { SessionService } from "../services/sessionService";
import {
  InsertsessionSchema as InsertsessionSchema,
  UpdatesessionSchema as UpdatesessionSchema,
  SelectsessionSchema as SelectsessionSchema,
} from "@/validators/zod";

const listSession = os
  .output(z.array(SelectsessionSchema))
  .handler(async () => {
    return await SessionService.getAll();
  });

const getSession = os
  .input(z.object({ id: z.number() }))
  .output(SelectsessionSchema.nullable())
  .handler(async ({ input }) => {
    return await SessionService.getById(input.id);
  });

const createSession = os
  .input(InsertsessionSchema)
  .output(SelectsessionSchema)
  .handler(async ({ input }) => {
    return await SessionService.create(input);
  });

const updateSession = os
  .input(z.object({ id: z.number(), data: UpdatesessionSchema }))
  .output(SelectsessionSchema)
  .handler(async ({ input }) => {
    return await SessionService.update(input.id, input.data);
  });

const deleteSession = os
  .input(z.object({ id: z.number() }))
  .output(z.boolean())
  .handler(async ({ input }) => {
    return await SessionService.delete(input.id);
  });

export const sessionRouter = {
  list: listSession,
  get: getSession,
  create: createSession,
  update: updateSession,
  delete: deleteSession,
};
