// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

// Generated by @drzl/generator-orpc
// Router for table: setting
import { os } from "@orpc/server";
import { z } from "zod";
import { SettingService } from "../services/settingService";
import {
  InsertsettingSchema as InsertsettingSchema,
  UpdatesettingSchema as UpdatesettingSchema,
  SelectsettingSchema as SelectsettingSchema,
} from "@/validators/zod";

const listSetting = os
  .output(z.array(SelectsettingSchema))
  .handler(async () => {
    return await SettingService.getAll();
  });

const getSetting = os
  .input(z.object({ id: z.number() }))
  .output(SelectsettingSchema.nullable())
  .handler(async ({ input }) => {
    return await SettingService.getById(input.id);
  });

const createSetting = os
  .input(InsertsettingSchema)
  .output(SelectsettingSchema)
  .handler(async ({ input }) => {
    return await SettingService.create(input);
  });

const updateSetting = os
  .input(z.object({ id: z.number(), data: UpdatesettingSchema }))
  .output(SelectsettingSchema)
  .handler(async ({ input }) => {
    return await SettingService.update(input.id, input.data);
  });

const deleteSetting = os
  .input(z.object({ id: z.number() }))
  .output(z.boolean())
  .handler(async ({ input }) => {
    return await SettingService.delete(input.id);
  });

export const settingRouter = {
  list: listSetting,
  get: getSetting,
  create: createSetting,
  update: updateSetting,
  delete: deleteSetting,
};
