// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

// Generated by @drzl/generator-orpc
// Router for table: stat
import { os } from "@orpc/server";
import { z } from "zod";
import { StatService } from "../services/statService";
import {
  InsertstatSchema as InsertstatSchema,
  UpdatestatSchema as UpdatestatSchema,
  SelectstatSchema as SelectstatSchema,
} from "@/validators/zod";

const listStat = os.output(z.array(SelectstatSchema)).handler(async () => {
  return await StatService.getAll();
});

const getStat = os
  .input(z.object({ id: z.number() }))
  .output(SelectstatSchema.nullable())
  .handler(async ({ input }) => {
    return await StatService.getById(input.id);
  });

const createStat = os
  .input(InsertstatSchema)
  .output(SelectstatSchema)
  .handler(async ({ input }) => {
    return await StatService.create(input);
  });

const updateStat = os
  .input(z.object({ id: z.number(), data: UpdatestatSchema }))
  .output(SelectstatSchema)
  .handler(async ({ input }) => {
    return await StatService.update(input.id, input.data);
  });

const deleteStat = os
  .input(z.object({ id: z.number() }))
  .output(z.boolean())
  .handler(async ({ input }) => {
    return await StatService.delete(input.id);
  });

export const statRouter = {
  list: listStat,
  get: getStat,
  create: createStat,
  update: updateStat,
  delete: deleteStat,
};
