// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

// Generated by @drzl/generator-orpc
// Router for table: user
import { os } from "@orpc/server";
import { z } from "zod";
import { UserService } from "../services/userService";
import {
  InsertuserSchema as InsertuserSchema,
  UpdateuserSchema as UpdateuserSchema,
  SelectuserSchema as SelectuserSchema,
} from "@/validators/zod";

const listUser = os.output(z.array(SelectuserSchema)).handler(async () => {
  return await UserService.getAll();
});

const getUser = os
  .input(z.object({ id: z.number() }))
  .output(SelectuserSchema.nullable())
  .handler(async ({ input }) => {
    return await UserService.getById(input.id);
  });

const createUser = os
  .input(InsertuserSchema)
  .output(SelectuserSchema)
  .handler(async ({ input }) => {
    return await UserService.create(input);
  });

const updateUser = os
  .input(z.object({ id: z.number(), data: UpdateuserSchema }))
  .output(SelectuserSchema)
  .handler(async ({ input }) => {
    return await UserService.update(input.id, input.data);
  });

const deleteUser = os
  .input(z.object({ id: z.number() }))
  .output(z.boolean())
  .handler(async ({ input }) => {
    return await UserService.delete(input.id);
  });

export const userRouter = {
  list: listUser,
  get: getUser,
  create: createUser,
  update: updateUser,
  delete: deleteUser,
};
