// Generated by DRZL (@drzl/*)
// Generated output is granted to you under your project's license.
// You may use, copy, modify, and distribute without attribution.

// Generated by @drzl/generator-orpc
// Router for table: verification
import { os } from "@orpc/server";
import { z } from "zod";
import { VerificationService } from "../services/verificationService";
import {
  InsertverificationSchema as InsertverificationSchema,
  UpdateverificationSchema as UpdateverificationSchema,
  SelectverificationSchema as SelectverificationSchema,
} from "@/validators/zod";

const listVerification = os
  .output(z.array(SelectverificationSchema))
  .handler(async () => {
    return await VerificationService.getAll();
  });

const getVerification = os
  .input(z.object({ id: z.number() }))
  .output(SelectverificationSchema.nullable())
  .handler(async ({ input }) => {
    return await VerificationService.getById(input.id);
  });

const createVerification = os
  .input(InsertverificationSchema)
  .output(SelectverificationSchema)
  .handler(async ({ input }) => {
    return await VerificationService.create(input);
  });

const updateVerification = os
  .input(z.object({ id: z.number(), data: UpdateverificationSchema }))
  .output(SelectverificationSchema)
  .handler(async ({ input }) => {
    return await VerificationService.update(input.id, input.data);
  });

const deleteVerification = os
  .input(z.object({ id: z.number() }))
  .output(z.boolean())
  .handler(async ({ input }) => {
    return await VerificationService.delete(input.id);
  });

export const verificationRouter = {
  list: listVerification,
  get: getVerification,
  create: createVerification,
  update: updateVerification,
  delete: deleteVerification,
};
